### ISSUE TITLE
Build and push docker image on tags

### ISSUE THREAD

**Issue by 0xlaine** [pylonboard/dotnet-pylonboard-monolith#5]
Something like this in the workflow configuration file:
```
on:
  push:
    tags:
    - '*'
```

And for building the docker image this seems to be a good article:
https://blog.hildenco.com/2020/10/building-and-hosting-docker-images-on.html
